edition: 3.0.0
name: hellodoctor
access: default
resources:
  login:
    component: fc3
    props:
      region: ${env('region')}
      description: ''
      timeout: 60
      internetAccess: true
      functionName: login
      runtime: go1
      cpu: 0.05
      instanceConcurrency: 20
      memorySize: 128
      environmentVariables:
        AppId: ${env('AppId')}
        AccessKeyId: ${env('AccessKeyId')}
        LD_LIBRARY_PATH: >-
          /code:/code/lib:/usr/local/lib:/opt/lib
        AccessKeySecret: ${env('AccessKeySecret')}
        EndPoint: ${env('EndPoint')}
        AppSecret: ${env('AppSecret')}
      handler: main
      Disk: 512
      code: target/login
      triggers:
        - triggerConfig:
            methods:
              - GET
            authType: anonymous
            disableURLInternet: false
          triggerName: defaultTrigger
          description: ''
          qualifier: LATEST
          triggerType: http
    actions:
      pre-deploy:
        - run: mkdir target
          path: ./
        - run: bash -c "source /root/.gvm/scripts/gvm && gvm install go1.21.7 && gvm use go1.21.7 && go mod vendor && GO111MODULE=on CGO_ENABLED=0 GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags='-s -w' -o=target/login user/login/main.go"
          path: ./
        - run: chmod a+x login
          path: ./target