edition: 3.0.0
name: hellodoctor
access: default
resources:
  login:
    component: fc3
    props:
      region: ${env('region')}
      description: ''
      timeout: 60
      internetAccess: true
      functionName: login
      runtime: go1
      cpu: 0.05
      instanceConcurrency: 20
      memorySize: 128
      environmentVariables:
        AppId: ${env('AppId')}
        AccessKeyId: ${env('AccessKeyId')}
        LD_LIBRARY_PATH: >-
          /code:/code/lib:/usr/local/lib:/opt/lib
        AccessKeySecret: ${env('AccessKeySecret')}
        EndPoint: ${env('EndPoint')}
        AppSecret: ${env('AppSecret')}
      code: target/user_login
      triggers:
        - triggerConfig:
            methods:
              - GET
            authType: anonymous
            disableURLInternet: false
          triggerName: defaultTrigger
          description: ''
          qualifier: LATEST
          triggerType: http
    actions:
      pre-deploy:
        - run: go version
          path: ./
        - run: GO111MODULE=on CGO_ENABLED=0 GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o target/login main.go
          path: user/login
        - run: chmod a+x login
          path: target
      success-deploy:
        - run: rm login
          path: target