templates:
  template.yml:
    serverless-devs-check:
      nslookup:
        event: default_evt
        events:
          default_evt:
            type: file
            value: serverless-devs-check/nslookup/event.evt
